version: '3.3'

services:
  app:
    image: taiidani/uaa:latest
    networks:
      - default
      - traefik_default
    deploy:
      labels:
        - "traefik.frontend.rule=Host: uaa.ryannixon.com"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_default"

networks:
  traefik_default:
    external: true
