version: '2'

services:
  apache:
    image: php:5.6.20-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  composer:
    image: composer/composer:latest
    command: install
    volumes:
      - .:/app